parser: babel-eslint

extends: "eslint:recommended"

ecmaFeatures:
  modules: true

env:
  browser: true
  node: true
  commonjs: true
  es6: true

rules:
  no-console: 0
  no-unused-vars: 1

globals:
